#!/usr/bin/env python3
"""
scripts/gen_lib_registry.py
Scans src/std/*/fluxa_std_*.h for FLUXA_LIB_EXPORT blocks and generates
src/lib_registry_gen.h — the single file the runtime includes to know
about all available libs.

Run automatically by 'make build'. Never edit lib_registry_gen.h by hand.

FLUXA_LIB_EXPORT format (place at the end of your lib header):
    FLUXA_LIB_EXPORT(
        name     = "pid",
        toml_key = "std.pid",
        owner    = "pid",
        call     = fluxa_std_pid_call,
        rt_aware = 0
    )

Fields:
    name     — identifier used in import statement: import std <name>
    toml_key — key in [libs] section: std.pid = "1.0"
    owner    — string compared against lib.fn() call owner (usually = name)
    call     — C function name of the dispatch function
    rt_aware — 1 if dispatch takes void *rt_ptr as last arg (flxthread pattern)
               0 for standard signature
"""
import re
import sys
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STD_DIR   = os.path.join(REPO_ROOT, "src", "std")
OUT_FILE  = os.path.join(REPO_ROOT, "src", "lib_registry_gen.h")

EXPORT_RE = re.compile(
    r'FLUXA_LIB_EXPORT\s*\(\s*(.*?)\s*\)',
    re.DOTALL
)
FIELD_RE = re.compile(r'(\w+)\s*=\s*"?([^",\n]+)"?\s*,?')

def parse_export(block):
    fields = {}
    for m in FIELD_RE.finditer(block):
        fields[m.group(1).strip()] = m.group(2).strip().strip('"')
    return fields

def read_fluxa_libs():
    """Read fluxa.libs to get build-time enable/disable per lib.
    Returns dict: toml_key -> True/False  e.g. {"std.math": True, ...}
    If fluxa.libs not found, all libs default to enabled."""
    enabled = {}
    libs_path = os.path.join(REPO_ROOT, "fluxa.libs")
    if not os.path.isfile(libs_path):
        return enabled  # empty = all enabled by default
    in_build = False
    with open(libs_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line == "[libs.build]":
                in_build = True
                continue
            if line.startswith("["):
                in_build = False
                continue
            if in_build and "=" in line:
                key, _, val = line.partition("=")
                key = key.strip()
                val = val.strip().lower().split("#")[0].strip()
                enabled[key] = (val == "true")
    return enabled


def scan_libs():
    libs = []
    fluxa_libs = read_fluxa_libs()

    if not os.path.isdir(STD_DIR):
        print(f"ERROR: {STD_DIR} not found", file=sys.stderr)
        sys.exit(1)

    for lib_dir in sorted(os.listdir(STD_DIR)):
        lib_path = os.path.join(STD_DIR, lib_dir)
        if not os.path.isdir(lib_path):
            continue
        # Find the fluxa_std_*.h header — filename may differ from dir name
        headers = [f for f in os.listdir(lib_path) if f.startswith("fluxa_std_") and f.endswith(".h")]
        if not headers:
            continue
        header = os.path.join(lib_path, sorted(headers)[0])
        with open(header, "r", encoding="utf-8") as f:
            content = f.read()
        for m in EXPORT_RE.finditer(content):
            fields = parse_export(m.group(1))
            required = {"name", "toml_key", "owner", "call"}
            missing = required - fields.keys()
            if missing:
                print(f"WARNING: {header}: FLUXA_LIB_EXPORT missing fields: {missing}",
                      file=sys.stderr)
                continue
            if "rt_aware" not in fields:
                fields["rt_aware"] = "0"
            fields["header"] = os.path.relpath(header, os.path.join(REPO_ROOT, "src"))
            # Guard is based on the lib name (from FLUXA_LIB_EXPORT), not dir name
            # e.g. name="strings" in dir "str" → FLUXA_STD_STRINGS
            fields["guard"]  = f"FLUXA_STD_{fields['name'].upper()}"
            # Check fluxa.libs — default enabled if not listed
            toml_key = fields.get("toml_key", f"std.{fields['name']}")
            fields["build_enabled"] = fluxa_libs.get(toml_key, True)
            # Duplicate name detection — error, not warning
            dup = next((l for l in libs if l["name"] == fields["name"]), None)
            if dup:
                print(f"ERROR: duplicate lib name '{fields['name']}':", file=sys.stderr)
                print(f"  first:  {dup['header']}", file=sys.stderr)
                print(f"  second: {fields['header']}", file=sys.stderr)
                print(f"  Each lib name must be globally unique.", file=sys.stderr)
                sys.exit(1)
            libs.append(fields)

    return libs

def generate(libs):
    lines = []
    lines.append("/* lib_registry_gen.h — AUTO-GENERATED by scripts/gen_lib_registry.py")
    lines.append(" * DO NOT EDIT. Run 'make build' to regenerate.")
    lines.append(" * Add a new lib: create src/std/<name>/fluxa_std_<name>.h")
    lines.append(" * with a FLUXA_LIB_EXPORT(...) block at the end.")
    lines.append(" */")
    lines.append("#ifndef LIB_REGISTRY_GEN_H")
    lines.append("#define LIB_REGISTRY_GEN_H")
    lines.append("")
    lines.append('#include "scope.h"')
    lines.append('#include "err.h"')
    lines.append("")

    # Conditional includes — each lib only if its guard is defined
    lines.append("/* toml_config.h must precede lib includes for FluxaConfig typedef */")
    lines.append('#include "toml_config.h"')
    lines.append("")
    lines.append("/* ── Conditional lib includes ─────────────────────────────────────── */")
    for lib in libs:
        lines.append(f'#ifdef {lib["guard"]}')
        lines.append(f'#  include "{lib["header"]}"')
        lines.append(f'#endif')
    lines.append("")

    # Dispatch function forward declarations for rt_aware libs
    rt_aware = [l for l in libs if l["rt_aware"] == "1"]
    if rt_aware:
        lines.append("/* ── rt_aware forward declarations ────────────────────────────────── */")
        for lib in rt_aware:
            lines.append(f'#ifdef {lib["guard"]}')
            lines.append(f'extern Value {lib["call"]}(const char *, const Value *, int,')
            lines.append(f'                            ErrStack *, int *, int, void *);')
            lines.append(f'#endif')
        lines.append("")

    # FluxaLibEntry struct
    lines.append("/* ── Registry entry ───────────────────────────────────────────────── */")
    lines.append('#include "toml_config.h"')
    lines.append("")
    lines.append("typedef Value (*FluxaLibCallFn)(const char *, const Value *, int,")
    lines.append("                                ErrStack *, int *, int);")
    lines.append("typedef Value (*FluxaLibCallRtFn)(const char *, const Value *, int,")
    lines.append("                                  ErrStack *, int *, int, void *);")
    lines.append("typedef Value (*FluxaLibCallCfgFn)(const char *, const Value *, int,")
    lines.append("                                   ErrStack *, int *, int,")
    lines.append("                                   const FluxaConfig *);")
    lines.append("")
    lines.append("typedef struct {")
    lines.append('    const char       *name;      /* import std <n>                  */')
    lines.append('    const char       *toml_key;  /* "std.pid" in [libs]             */')
    lines.append('    const char       *owner;     /* lib.fn() owner string           */')
    lines.append('    FluxaLibCallFn    call;      /* standard dispatch                */')
    lines.append('    FluxaLibCallRtFn  call_rt;   /* rt-aware (flxthread pattern)     */')
    lines.append('    FluxaLibCallCfgFn call_cfg;  /* cfg-aware (json/csv pattern)     */')
    lines.append('    int               rt_aware;  /* 1 = use call_rt                 */')
    lines.append('    int               cfg_aware; /* 1 = use call_cfg                */')
    lines.append('    int               enabled;   /* 1 = compiled in (#ifdef)        */')
    lines.append("} FluxaLibEntry;")
    lines.append("")
    lines.append("")

    # The registry array — one entry per lib
    lines.append("/* ── Registry array ───────────────────────────────────────────────── */")
    lines.append("static const FluxaLibEntry fluxa_lib_registry[] = {")
    for lib in libs:
        g = lib["guard"]
        name     = lib["name"]
        toml_key = lib["toml_key"]
        owner    = lib["owner"]
        call     = lib["call"]
        rt       = lib["rt_aware"] == "1"

        lines.append(f'#ifdef {g}')
        cfg = lib.get("cfg_aware", "0") == "1"
        if rt:
            lines.append(f'    {{ "{name}", "{toml_key}", "{owner}", NULL, {call}, NULL, 1, 0, 1 }},')
        elif cfg:
            lines.append(f'    {{ "{name}", "{toml_key}", "{owner}", NULL, NULL, {call}, 0, 1, 1 }},')
        else:
            lines.append(f'    {{ "{name}", "{toml_key}", "{owner}", {call}, NULL, NULL, 0, 0, 1 }},')
        lines.append(f'#else')
        lines.append(f'    {{ "{name}", "{toml_key}", "{owner}", NULL, NULL, NULL, {1 if rt else 0}, {1 if cfg else 0}, 0 }},')
        lines.append(f'#endif')
    lines.append("};")
    lines.append("")
    lines.append(f"#define FLUXA_LIB_COUNT {len(libs)}")
    lines.append("")

    # Helper: find entry by name
    lines.append("/* ── Helpers ──────────────────────────────────────────────────────── */")
    lines.append("static inline const FluxaLibEntry *")
    lines.append("fluxa_lib_find_by_name(const char *name) {")
    lines.append("    for (int i = 0; i < FLUXA_LIB_COUNT; i++)")
    lines.append('        if (fluxa_lib_registry[i].name &&')
    lines.append('            strcmp(fluxa_lib_registry[i].name, name) == 0)')
    lines.append("            return &fluxa_lib_registry[i];")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("static inline const FluxaLibEntry *")
    lines.append("fluxa_lib_find_by_owner(const char *owner) {")
    lines.append("    for (int i = 0; i < FLUXA_LIB_COUNT; i++)")
    lines.append('        if (fluxa_lib_registry[i].owner &&')
    lines.append('            strcmp(fluxa_lib_registry[i].owner, owner) == 0)')
    lines.append("            return &fluxa_lib_registry[i];")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("static inline const FluxaLibEntry *")
    lines.append("fluxa_lib_find_by_toml_key(const char *key) {")
    lines.append("    for (int i = 0; i < FLUXA_LIB_COUNT; i++)")
    lines.append('        if (fluxa_lib_registry[i].toml_key &&')
    lines.append('            strcmp(fluxa_lib_registry[i].toml_key, key) == 0)')
    lines.append("            return &fluxa_lib_registry[i];")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* LIB_REGISTRY_GEN_H */")

    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    libs = scan_libs()
    if not libs:
        print("WARNING: no libs found in src/std/", file=sys.stderr)
    out = generate(libs)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(out)

    # Write Makefile fragment: FLUXA_LIBS_CFLAGS for build-enabled libs only
    mk_path = os.path.join(REPO_ROOT, "src", "lib_registry_flags.mk")
    enabled_names = [l["name"] for l in libs if l.get("build_enabled", True)]
    disabled_names = [l["name"] for l in libs if not l.get("build_enabled", True)]
    with open(mk_path, "w") as f:
        f.write("# lib_registry_flags.mk — AUTO-GENERATED by scripts/gen_lib_registry.py\n")
        f.write("# DO NOT EDIT. Controls which libs enter the binary.\n")
        f.write("# Edit fluxa.libs then run: make build\n\n")
        f.write("# Make variables — read by lib.mk files to gate FLUXA_STD_* flags\n")
        for name in enabled_names:
            f.write(f"FLUXA_BUILDTIME_{name.upper()} := 1\n")
        if disabled_names:
            f.write("\n# Libs disabled in fluxa.libs:\n")
            for name in disabled_names:
                f.write(f"FLUXA_BUILDTIME_{name.upper()} := 0\n")

    enabled_count = sum(1 for l in libs if l.get("build_enabled", True))
    disabled_count = len(libs) - enabled_count
    print(f"[gen_lib_registry] generated {OUT_FILE} "
          f"({len(libs)} libs: {enabled_count} enabled, {disabled_count} disabled)")
