/* lib_registry_gen.h — AUTO-GENERATED by scripts/gen_lib_registry.py
 * DO NOT EDIT. Run 'make build' to regenerate.
 * Add a new lib: create src/std/<name>/fluxa_std_<name>.h
 * with a FLUXA_LIB_EXPORT(...) block at the end.
 */
#ifndef LIB_REGISTRY_GEN_H
#define LIB_REGISTRY_GEN_H

#include "scope.h"
#include "err.h"

/* toml_config.h must precede lib includes for FluxaConfig typedef */
#include "toml_config.h"

/* ── Conditional lib includes ─────────────────────────────────────── */
#ifdef FLUXA_STD_CRYPTO
#  include "std/crypto/fluxa_std_crypto.h"
#endif
#ifdef FLUXA_STD_CSV
#  include "std/csv/fluxa_std_csv.h"
#endif
#ifdef FLUXA_STD_FLXTHREAD
#  include "std/flxthread/fluxa_std_flxthread.h"
#endif
#ifdef FLUXA_STD_HTTP
#  include "std/http/fluxa_std_http.h"
#endif
#ifdef FLUXA_STD_I2C
#  include "std/i2c/fluxa_std_i2c.h"
#endif
#ifdef FLUXA_STD_JSON
#  include "std/json/fluxa_std_json.h"
#endif
#ifdef FLUXA_STD_LIBV
#  include "std/libv/fluxa_std_libv.h"
#endif
#ifdef FLUXA_STD_MATH
#  include "std/math/fluxa_std_math.h"
#endif
#ifdef FLUXA_STD_MCP
#  include "std/mcp/fluxa_std_mcp.h"
#endif
#ifdef FLUXA_STD_MQTT
#  include "std/mqtt/fluxa_std_mqtt.h"
#endif
#ifdef FLUXA_STD_PID
#  include "std/pid/fluxa_std_pid.h"
#endif
#ifdef FLUXA_STD_SERIAL
#  include "std/serial/fluxa_std_serial.h"
#endif
#ifdef FLUXA_STD_SQLITE
#  include "std/sqlite/fluxa_std_sqlite.h"
#endif
#ifdef FLUXA_STD_STRINGS
#  include "std/str/fluxa_std_strings.h"
#endif
#ifdef FLUXA_STD_TIME
#  include "std/time/fluxa_std_time.h"
#endif

/* ── rt_aware forward declarations ────────────────────────────────── */
#ifdef FLUXA_STD_FLXTHREAD
extern Value fluxa_std_flxthread_call(const char *, const Value *, int,
                            ErrStack *, int *, int, void *);
#endif

/* ── Registry entry ───────────────────────────────────────────────── */
#include "toml_config.h"

typedef Value (*FluxaLibCallFn)(const char *, const Value *, int,
                                ErrStack *, int *, int);
typedef Value (*FluxaLibCallRtFn)(const char *, const Value *, int,
                                  ErrStack *, int *, int, void *);
typedef Value (*FluxaLibCallCfgFn)(const char *, const Value *, int,
                                   ErrStack *, int *, int,
                                   const FluxaConfig *);

typedef struct {
    const char       *name;      /* import std <n>                  */
    const char       *toml_key;  /* "std.pid" in [libs]             */
    const char       *owner;     /* lib.fn() owner string           */
    FluxaLibCallFn    call;      /* standard dispatch                */
    FluxaLibCallRtFn  call_rt;   /* rt-aware (flxthread pattern)     */
    FluxaLibCallCfgFn call_cfg;  /* cfg-aware (json/csv pattern)     */
    int               rt_aware;  /* 1 = use call_rt                 */
    int               cfg_aware; /* 1 = use call_cfg                */
    int               enabled;   /* 1 = compiled in (#ifdef)        */
} FluxaLibEntry;


/* ── Registry array ───────────────────────────────────────────────── */
static const FluxaLibEntry fluxa_lib_registry[] = {
#ifdef FLUXA_STD_CRYPTO
    { "crypto", "std.crypto", "crypto", fluxa_std_crypto_call, NULL, NULL, 0, 0, 1 },
#else
    { "crypto", "std.crypto", "crypto", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_CSV
    { "csv", "std.csv", "csv", fluxa_std_csv_call, NULL, NULL, 0, 0, 1 },
#else
    { "csv", "std.csv", "csv", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_FLXTHREAD
    { "flxthread", "std.flxthread", "ft", NULL, fluxa_std_flxthread_call, NULL, 1, 0, 1 },
#else
    { "flxthread", "std.flxthread", "ft", NULL, NULL, NULL, 1, 0, 0 },
#endif
#ifdef FLUXA_STD_HTTP
    { "http", "std.http", "http", fluxa_std_http_call, NULL, NULL, 0, 0, 1 },
#else
    { "http", "std.http", "http", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_I2C
    { "i2c", "std.i2c", "i2c", fluxa_std_i2c_call, NULL, NULL, 0, 0, 1 },
#else
    { "i2c", "std.i2c", "i2c", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_JSON
    { "json", "std.json", "json", NULL, NULL, fluxa_std_json_call, 0, 1, 1 },
#else
    { "json", "std.json", "json", NULL, NULL, NULL, 0, 1, 0 },
#endif
#ifdef FLUXA_STD_LIBV
    { "libv", "std.libv", "libv", fluxa_std_libv_call, NULL, NULL, 0, 0, 1 },
#else
    { "libv", "std.libv", "libv", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_MATH
    { "math", "std.math", "math", fluxa_std_math_call, NULL, NULL, 0, 0, 1 },
#else
    { "math", "std.math", "math", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_MCP
    { "mcp", "std.mcp", "mcp", fluxa_std_mcp_call, NULL, NULL, 0, 0, 1 },
#else
    { "mcp", "std.mcp", "mcp", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_MQTT
    { "mqtt", "std.mqtt", "mqtt", fluxa_std_mqtt_call, NULL, NULL, 0, 0, 1 },
#else
    { "mqtt", "std.mqtt", "mqtt", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_PID
    { "pid", "std.pid", "pid", fluxa_std_pid_call, NULL, NULL, 0, 0, 1 },
#else
    { "pid", "std.pid", "pid", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_SERIAL
    { "serial", "std.serial", "serial", fluxa_std_serial_call, NULL, NULL, 0, 0, 1 },
#else
    { "serial", "std.serial", "serial", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_SQLITE
    { "sqlite", "std.sqlite", "sqlite", fluxa_std_sqlite_call, NULL, NULL, 0, 0, 1 },
#else
    { "sqlite", "std.sqlite", "sqlite", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_STRINGS
    { "strings", "std.strings", "strings", fluxa_std_strings_call, NULL, NULL, 0, 0, 1 },
#else
    { "strings", "std.strings", "strings", NULL, NULL, NULL, 0, 0, 0 },
#endif
#ifdef FLUXA_STD_TIME
    { "time", "std.time", "time", fluxa_std_time_call, NULL, NULL, 0, 0, 1 },
#else
    { "time", "std.time", "time", NULL, NULL, NULL, 0, 0, 0 },
#endif
};

#define FLUXA_LIB_COUNT 15

/* ── Helpers ──────────────────────────────────────────────────────── */
static inline const FluxaLibEntry *
fluxa_lib_find_by_name(const char *name) {
    for (int i = 0; i < FLUXA_LIB_COUNT; i++)
        if (fluxa_lib_registry[i].name &&
            strcmp(fluxa_lib_registry[i].name, name) == 0)
            return &fluxa_lib_registry[i];
    return NULL;
}

static inline const FluxaLibEntry *
fluxa_lib_find_by_owner(const char *owner) {
    for (int i = 0; i < FLUXA_LIB_COUNT; i++)
        if (fluxa_lib_registry[i].owner &&
            strcmp(fluxa_lib_registry[i].owner, owner) == 0)
            return &fluxa_lib_registry[i];
    return NULL;
}

static inline const FluxaLibEntry *
fluxa_lib_find_by_toml_key(const char *key) {
    for (int i = 0; i < FLUXA_LIB_COUNT; i++)
        if (fluxa_lib_registry[i].toml_key &&
            strcmp(fluxa_lib_registry[i].toml_key, key) == 0)
            return &fluxa_lib_registry[i];
    return NULL;
}

#endif /* LIB_REGISTRY_GEN_H */
